inherit_mode:
  merge:
    - Exclude

require:
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rspec.yml
  - .rubocop/minitest.yml
  - .rubocop/custom.yml
  - .rubocop/strict.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.7